#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "elabftw"
name = "eLabFTW"
description.en = "Open source electronic lab notebook for research labs"
description.fr = "Cahier de laboratoire électronique open source pour les laboratoires de recherche"

version = "4.2.4~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://www.elabftw.net"
demo = "https://demo.elabftw.net/login.php"
admindoc = "https://doc.elabftw.net/"
code = "https://github.com/elabftw/elabftw"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, eLabFTW will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, eLabFTW sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/elabftw/elabftw/archive/refs/tags/4.2.4.zip"
    sha256 = "1922b5dc3eeb6e6feb1b36a041113abb4e43cb19eb6fe5bd211440efc7ef10a4"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "brotli",
        "zopfli",
        "php-bcmath",
        "php8.0-curl",
        "php8.0-ctype",
        "php8.0-dev",
        "php8.0-dom",
        "php8.0-exif",
        "php8.0-gd",
        "php8.0-gettext",
        "php8.0-fileinfo",
        "php8.0-fpm",
        "php8.0-json",
        "php8.0-intl",
        "php8.0-ldap",
        "php8.0-mbstring",
        "php8.0-opcache",
        "php8.0-mysql",
        "php8.0-imagick",
        "php8.0-phar",
        "php8.0-redis",
        "php8.0-simplexml",
        "php8.0-tokenizer",
        "php8.0-xml",
        "php8.0-xmlwriter",
        "php8.0-zip",
    ]


    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]

    [resources.database]
    type = "mysql"
